"""
FORGE Skill Generator (Hermes-inspired)
After 5+ tool calls / complex sessions → auto-generate a SKILL.md
Stored in memory, searchable by FTS5, loaded at session start if relevant.
"""
from __future__ import annotations

import time
from dataclasses import dataclass

from forge.memory import ForgeMemory, Skill, SessionRecord


SKILL_TEMPLATE = """# {title}

**Task Type:** {task_type}
**Generated:** {date}
**Source Sessions:** {session_count}

## When to Use
{when_to_use}

## Approach
{approach}

## Key Patterns
{patterns}

## Pitfalls to Avoid
{pitfalls}

---
*Auto-generated by FORGE skill engine*
"""


@dataclass
class GeneratedSkill:
    title:        str
    task_type:    str
    when_to_use:  str
    approach:     str
    patterns:     str
    pitfalls:     str


class SkillGenerator:
    """
    Monitors sessions and generates skill files when:
    - Session count for a task type crosses threshold (default: 5)
    - User explicitly runs `forge learn`
    - A session is marked as "solved a hard problem"
    """

    def __init__(self, memory: ForgeMemory, threshold: int = 5):
        self._memory    = memory
        self._threshold = threshold
        self._session_buffer: list[SessionRecord] = []
        self._tool_call_count = 0

    def record_tool_call(self) -> None:
        self._tool_call_count += 1

    def reset_tool_calls(self) -> None:
        self._tool_call_count = 0

    def should_generate(self) -> bool:
        return self._tool_call_count >= self._threshold

    async def maybe_generate(
        self,
        project:   str,
        task_type: str,
        sessions:  list[dict],
        router,            # ForgeRouter, passed in to call LLM
    ) -> Skill | None:
        """
        If threshold crossed, use LLM to generate a skill from recent sessions.
        Uses fast_free tier — skill generation doesn't need best model.
        """
        if not self.should_generate():
            return None

        if not sessions:
            return None

        # Build context from recent sessions
        session_summary = "\n\n".join([
            f"Task: {s['prompt'][:200]}\nResponse summary: {s['response'][:300]}"
            for s in sessions[:5]
        ])

        prompt = f"""Based on these {len(sessions)} coding sessions for task type '{task_type}',
generate a reusable skill document.

Sessions:
{session_summary}

Return a JSON object with these exact keys:
{{
  "title": "short descriptive skill name",
  "when_to_use": "1-2 sentences on when to apply this skill",
  "approach": "step-by-step approach, 3-5 steps",
  "patterns": "key code patterns or templates discovered",
  "pitfalls": "common mistakes to avoid"
}}

JSON only. No preamble."""

        try:
            result = await router.route(
                prompt=prompt,
                system="You are a skill extraction engine. Output valid JSON only.",
            )

            if not result.response.success:
                return None

            import json
            content = result.response.content.strip()
            # Strip markdown fences if present
            if content.startswith("```"):
                content = content.split("```")[1]
                if content.startswith("json"):
                    content = content[4:]
            content = content.strip().rstrip("```").strip()

            data = json.loads(content)

            skill_md = SKILL_TEMPLATE.format(
                title=data["title"],
                task_type=task_type,
                date=time.strftime("%Y-%m-%d"),
                session_count=len(sessions),
                when_to_use=data["when_to_use"],
                approach=data["approach"],
                patterns=data["patterns"],
                pitfalls=data["pitfalls"],
            )

            skill = Skill(
                title=data["title"],
                task_type=task_type,
                content=skill_md,
                project=project,
            )

            self._memory.save_skill(skill)
            self.reset_tool_calls()
            return skill

        except Exception as e:
            # Skill generation failing silently is fine
            return None

    def find_relevant_skills(self, prompt: str) -> list[dict]:
        """Search for skills relevant to current task."""
        return self._memory.search_skills(prompt, limit=2)
